### ISSUE TITLE
Can't Load Pretrained Model from Fresh

### ISSUE THREAD

**Issue by cdettmering** [miguelalonsojr/anyGPT#15]
Trying to run the pretrained model from a fresh pull results in the error:

```bash
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

Seems to be a problem with relying on a mapping created during the prep data / training step.

I should be able to run the pretrained model from a fresh install without running any other step.

**Comment by miguelalonsojr** [comment]
Issue addressed with this PR: https://github.com/any-LABS/anyGPT/pull/18
